#!/usr/bin/env python
"""#!/usr/bin/env -S uv run --script
## Run this script using uv
## init uv with `uv init && uv venv && source .venv/bin/activate`
## Check `skeletons/tools/py` for a list of currently preferred tools
"""

from dataclasses import dataclass


@dataclass
class CollectedSession:
    header_packet_format: int = 0
    header_game_year: int = 0
    header_game_major_version: int = 0
    header_game_minor_version: int = 0
    header_packet_version: int = 0
    header_session_uuid: str = "None"
    header_session_time: float = 0.0
    header_player_car_index: int = 0
    header_player2_car_index: int = 0
    session_weather: str = "None"
    session_track_temp_c: int = 0
    session_air_temp_c: int = 0
    session_total_race_laps: int = 0
    session_track_length_m: int = 0
    session_session_type: str = "None"
    session_track_id: str = "None"
    session_formula: int = 0
    session_session_time_remaining_seconds: int = 0
    session_session_duration_seconds: int = 0
    session_pit_speed_limit_kph: int = 0
    session_game_paused: int = 0
    session_is_spectating: int = 0
    session_spectator_car_index: int = 0
    session_sli_pro_native_support: str = "None"
    session_number_of_marshal_zones: int = 0
    session_safety_car_status: str = "None"
    session_network_game: str = "None"
    session_number_of_weather_forecast_samples: int = 0
    session_weather_forecast_accuracy: str = "None"
    session_ai_difficulty_level: int = 0
    session_season_link_id: str = "None"
    session_weekend_link_id: str = "None"
    session_session_link_id: str = "None"
    session_pit_stop_ideal_lap: int = 0
    session_pit_stop_latest_lap: int = 0
    session_pit_stop_rejoin_position: int = 0
    session_steering_assist: str = "None"
    session_braking_assist: str = "None"
    session_gearbox_assist: str = "None"
    session_pit_assist: str = "None"
    session_pit_release_assist: str = "None"
    session_ers_assist: str = "None"
    session_drs_assist: str = "None"
    session_dynamic_racing_line: str = "None"
    session_dynamic_racing_line_type: int = 0
    session_game_mode: str = "None"
    session_ruleset: str = "None"
    session_time_of_day: int = 0
    session_session_length: str = "None"
    session_speed_units_player1: str = "None"
    session_temp_units_player1: str = "None"
    session_speed_units_player2: str = "None"
    session_temp_units_player2: str = "None"
    session_number_of_safetycar_incidents: int = 0
    session_number_of_virtualsafetycar_incidents: int = 0
    session_number_of_red_flags: int = 0
    session_equal_car_performance: str = "None"
    session_recovery_mode: str = "None"
    session_flashback_limit: str = "None"
    session_surface_type: str = "None"
    session_low_fuel_mode: str = "None"
    session_race_starts: str = "None"
    session_tyre_temps: str = "None"
    session_pit_lane_tyre_sim: str = "None"
    session_car_damage: str = "None"
    session_car_damage_rate: str = "None"
    session_collisions: str = "None"
    session_collisions_first_lap_only: str = "None"
    session_multiplayer_unsafe_pit_release: str = "None"
    session_multiplayer_kick_for_griefing: str = "None"
    session_corner_cutting_stringency: str = "None"
    session_parc_ferme: str = "None"
    session_pit_stop_experience: str = "None"
    session_safety_car: str = "None"
    session_safety_car_experience: str = "None"
    session_formation_lap: str = "None"
    session_formation_lap_experience: str = "None"
    session_red_flags: str = "None"
    session_affects_licence_level_solo: str = "None"
    session_affects_licence_level_multiplayer: str = "None"
    session_number_of_sessions_in_weekend: int = 0
    session_sector_2_start_distance_m: float = 0.0
    session_sector_3_start_distance_m: float = 0.0
    event_fastest_lap_car_id: int = 0
    event_fastest_lap_seconds: float = 0.0
    event_retired_car_id: int = 0
    event_retirement_reason: str = "None"
    event_drs_disabled: bool = False
    event_drs_disabled_reason: str = "None"
    event_penalty_type: str = "None"
    event_penalty_infringement_type: str = "None"
    event_penalty_car_id_of_criminal: int = 0
    event_penalty_car_id_of_victim: int = 0
    event_penalty_time_gained: int = 0
    event_penalty_lap_number_of_offence: int = 0
    event_penalty_places_gained: int = 0
    event_speedtrap_is_overall_fastest_in_session: int = 0
    event_speedtrap_is_fastest_for_driver_session: int = 0
    event_speedtrap_car_id_of_fastest_in_session: int = 0
    event_speedtrap_fastest_speed_in_session_kph: float = 0.0
    event_collision_car_1_idx: int = 0
    event_collision_car_2_idx: int = 0
    event_safety_car_safety_car_type: str = "None"
    event_safety_car_safety_car_status: str = "None"


@dataclass
class PlayerCollectedCar:
    aaa_car_idx: str | int = 0
    event_speedtrap_speed_kph: str | float = 0.0
    motion_world_position_x: str | float = 0.0
    motion_world_position_y: str | float = 0.0
    motion_world_position_z: str | float = 0.0
    motion_world_velocity_x: str | float = 0.0
    motion_world_velocity_y: str | float = 0.0
    motion_world_velocity_z: str | float = 0.0
    motion_world_forward_direction_x: str | int = 0
    motion_world_forward_direction_y: str | int = 0
    motion_world_forward_direction_z: str | int = 0
    motion_world_right_direction_x: str | int = 0
    motion_world_right_direction_y: str | int = 0
    motion_world_right_direction_z: str | int = 0
    motion_g_force_lateral: str | float = 0.0
    motion_g_force_longitudinal: str | float = 0.0
    motion_g_force_vertical: str | float = 0.0
    motion_yaw_radians: str | float = 0.0
    motion_pitch_radians: str | float = 0.0
    motion_roll_radians: str | float = 0.0
    lapdata_last_lap_time_ms: str | int = 0
    lapdata_current_lap_time_ms: str | int = 0
    lapdata_sector1_time_ms_component: str | int = 0
    lapdata_sector1_time_minutes_component: str | int = 0
    lapdata_sector2_time_ms_component: str | int = 0
    lapdata_sector2_time_minutes_component: str | int = 0
    lapdata_delta_to_car_in_front_ms_component: str | int = 0
    lapdata_delta_to_car_in_front_minutes_component: str | int = 0
    lapdata_delta_to_leader_ms_component: str | int = 0
    lapdata_delta_to_leader_minutes_component: str | int = 0
    lapdata_lap_distance_travelled_m: str | float = 0.0
    lapdata_session_distance_travelled_m: str | float = 0.0
    lapdata_safety_car_delta: str | float = 0.0
    lapdata_car_position: str | int = 0
    lapdata_current_lap_number: str | int = 0
    lapdata_pit_status: str | int = 0
    lapdata_number_of_pit_stops: str | int = 0
    lapdata_sector: str | int = 0
    lapdata_current_lap_invalid: str | int = 0
    lapdata_penalties: str | int = 0
    lapdata_total_warnings: str | int = 0
    lapdata_corner_cutting_warnings: str | int = 0
    lapdata_number_unserved_drive_through_pens: str | int = 0
    lapdata_number_unserved_stop_go_pens: str | int = 0
    lapdata_grid_position: str | int = 0
    lapdata_driver_status: str | int = 0
    lapdata_result_status: str | int = 0
    lapdata_pit_lane_timer_active: str | int = 0
    lapdata_pit_lane_time_ms: str | int = 0
    lapdata_pit_lane_stop_time_ms: str | int = 0
    lapdata_pit_stop_must_serve_pen: str | int = 0
    lapdata_fastest_speed_trap_speed_kph: str | float = 0.0
    lapdata_fastest_speed_trap_lap: str | int = 0
    participants_is_ai_controlled_flag: str | int = 0
    participants_driver_id: str | int = 0
    participants_network_id: str | int = 0
    participants_team_id: str | int = 0
    participants_my_team_flag: str | int = 0
    participants_race_number: str | int = 0
    participants_nationality: str | int = 0
    participants_name: str = ""
    participants_network_telemetry_flag: str | int = 0
    participants_show_online_names: str | int = 0
    participants_f1_world_tech_level: str | int = 0
    participants_platform: str | int = 0
    participants_number_of_colours: str | int = 0
    participants_livery_red_1: str | int = 0
    participants_livery_green_1: str | int = 0
    participants_livery_blue_1: str | int = 0
    participants_livery_red_2: str | int = 0
    participants_livery_green_2: str | int = 0
    participants_livery_blue_2: str | int = 0
    participants_livery_red_3: str | int = 0
    participants_livery_green_3: str | int = 0
    participants_livery_blue_3: str | int = 0
    participants_livery_red_4: str | int = 0
    participants_livery_green_4: str | int = 0
    participants_livery_blue_4: str | int = 0
    setup_front_wing: str | int = 0
    setup_rear_wing: str | int = 0
    setup_on_throttle: str | int = 0
    setup_off_throttle: str | int = 0
    setup_front_camber: str | float = 0.0
    setup_rear_camber: str | float = 0.0
    setup_front_toe: str | float = 0.0
    setup_rear_toe: str | float = 0.0
    setup_front_suspension: str | int = 0
    setup_rear_suspension: str | int = 0
    setup_front_anti_roll_bar: str | int = 0
    setup_rear_anti_roll_bar: str | int = 0
    setup_front_suspension_height: str | int = 0
    setup_rear_suspension_height: str | int = 0
    setup_brake_pressure: str | int = 0
    setup_brake_bias: str | int = 0
    setup_engine_braking: str | int = 0
    setup_rear_left_tyre_pressure: str | float = 0.0
    setup_rear_right_tyre_pressure: str | float = 0.0
    setup_front_left_tyre_pressure: str | float = 0.0
    setup_front_right_tyre_pressure: str | float = 0.0
    setup_ballast: str | int = 0
    setup_fuel_load: str | float = 0.0
    telemetry_speed: str | int = 0
    telemetry_throttle: str | float = 0.0
    telemetry_steer: str | float = 0.0
    telemetry_brake: str | float = 0.0
    telemetry_clutch: str | int = 0
    telemetry_gear: str | int = 0
    telemetry_engine_rpm: str | int = 0
    telemetry_drs: str | int = 0
    telemetry_rev_lights_percent: str | int = 0
    telemetry_rev_lights_bit_value: str | int = 0
    telemetry_brakes_rl_temperature: str | int = 0
    telemetry_brakes_rr_temperature: str | int = 0
    telemetry_brakes_fl_temperature: str | int = 0
    telemetry_brakes_fr_temperature: str | int = 0
    telemetry_tyres_rl_surface_temperature: str | int = 0
    telemetry_tyres_rr_surface_temperature: str | int = 0
    telemetry_tyres_fl_surface_temperature: str | int = 0
    telemetry_tyres_fr_surface_temperature: str | int = 0
    telemetry_tyres_rl_inner_temperature: str | int = 0
    telemetry_tyres_rr_inner_temperature: str | int = 0
    telemetry_tyres_fl_inner_temperature: str | int = 0
    telemetry_tyres_fr_inner_temperature: str | int = 0
    telemetry_engine_temperature: str | int = 0
    telemetry_tyres_rl_pressure: str | float = 0.0
    telemetry_tyres_rr_pressure: str | float = 0.0
    telemetry_tyres_fl_pressure: str | float = 0.0
    telemetry_tyres_fr_pressure: str | float = 0.0
    telemetry_surface_rl_type: str | int = 0
    telemetry_surface_rr_type: str | int = 0
    telemetry_surface_fl_type: str | int = 0
    telemetry_surface_fr_type: str | int = 0
    status_traction_control: str | int = 0
    status_anti_lock_brakes: str | int = 0
    status_fuel_mix: str | int = 0
    status_front_brake_bias: str | int = 0
    status_pit_limiter_status: str | int = 0
    status_current_fuel_in_tank_kg: str | float = 0.0
    status_fuel_capacity: str | float = 0.0
    status_fuel_remaining_laps: str | float = 0.0
    status_max_rpm: str | int = 0
    status_idle_rpm: str | int = 0
    status_max_gears: str | int = 0
    status_drs_allowed: str | int = 0
    status_drs_activated_in_distance: str | int = 0
    status_actual_tyre_compound: str | int = 0
    status_visual_tyre_compound: str | int = 0
    status_tyre_age_laps: str | int = 0
    status_vehicle_flags_shown: str | int = 0
    status_engine_power_ice: str | float = 0.0
    status_engine_power_mguk: str | float = 0.0
    status_ers_store_energy: str | float = 0.0
    status_ers_deploy_mode: str | int = 0
    status_ers_harvested_mguk: str | float = 0.0
    status_ers_harvested_mgu_h: str | float = 0.0
    status_ers_deployed_this_lap: str | float = 0.0
    status_network_paused: str | int = 0
    classification_position: str | int = 0
    classification_num_laps: str | int = 0
    classification_grid_position: str | int = 0
    classification_points: str | int = 0
    classification_num_pit_stops: str | int = 0
    classification_result_status: str | int = 0
    classification_result_reason: str | int = 0
    classification_best_lap_time_in_ms: str | int = 0
    classification_total_race_time: str | float = 0.0
    classification_penalties_time: str | int = 0
    classification_num_penalties: str | int = 0
    classification_num_tyre_stints: str | int = 0
    classification_tyre_stint_1_actual_tyre: str | int = 0
    classification_tyre_stint_1_visual_tyre: str | int = 0
    classification_tyre_stint_1_end_lap: str | int = 0
    classification_tyre_stint_2_actual_tyre: str | int = 0
    classification_tyre_stint_2_visual_tyre: str | int = 0
    classification_tyre_stint_2_end_lap: str | int = 0
    classification_tyre_stint_3_actual_tyre: str | int = 0
    classification_tyre_stint_3_visual_tyre: str | int = 0
    classification_tyre_stint_3_end_lap: str | int = 0
    classification_tyre_stint_4_actual_tyre: str | int = 0
    classification_tyre_stint_4_visual_tyre: str | int = 0
    classification_tyre_stint_4_end_lap: str | int = 0
    classification_tyre_stint_5_actual_tyre: str | int = 0
    classification_tyre_stint_5_visual_tyre: str | int = 0
    classification_tyre_stint_5_end_lap: str | int = 0
    classification_tyre_stint_6_actual_tyre: str | int = 0
    classification_tyre_stint_6_visual_tyre: str | int = 0
    classification_tyre_stint_6_end_lap: str | int = 0
    classification_tyre_stint_7_actual_tyre: str | int = 0
    classification_tyre_stint_7_visual_tyre: str | int = 0
    classification_tyre_stint_7_end_lap: str | int = 0
    classification_tyre_stint_8_actual_tyre: str | int = 0
    classification_tyre_stint_8_visual_tyre: str | int = 0
    classification_tyre_stint_8_end_lap: str | int = 0
    damage_tyre_rl_wear_percentage: str | float = 0.0
    damage_tyre_rr_wear_percentage: str | float = 0.0
    damage_tyre_fl_wear_percentage: str | float = 0.0
    damage_tyre_fr_wear_percentage: str | float = 0.0
    damage_tyre_rl_damage_percentage: str | int = 0
    damage_tyre_rr_damage_percentage: str | int = 0
    damage_tyre_fl_damage_percentage: str | int = 0
    damage_tyre_fr_damage_percentage: str | int = 0
    damage_brakes_rl_damage_percentage: str | int = 0
    damage_brakes_rr_damage_percentage: str | int = 0
    damage_brakes_fl_damage_percentage: str | int = 0
    damage_brakes_fr_damage_percentage: str | int = 0
    damage_tyre_rl_blisters_percentage: str | int = 0
    damage_tyre_rr_blisters_percentage: str | int = 0
    damage_tyre_fl_blisters_percentage: str | int = 0
    damage_tyre_fr_blisters_percentage: str | int = 0
    damage_front_left_wing_damage_percentage: str | int = 0
    damage_front_right_wing_damage_percentage: str | int = 0
    damage_rear_wing_damage_percentage: str | int = 0
    damage_floor_damage_percentage: str | int = 0
    damage_diffuser_damage_percentage: str | int = 0
    damage_sidepod_damage_percentage: str | int = 0
    damage_drs_fault: str | int = 0
    damage_ers_fault: str | int = 0
    damage_gearbox_damage_percentage: str | int = 0
    damage_engine_damage_percentage: str | int = 0
    damage_engine_mguh_wear_percentage: str | int = 0
    damage_engine_es_wear_percentage: str | int = 0
    damage_engine_ce_wear_percentage: str | int = 0
    damage_engine_ice_wear_percentage: str | int = 0
    damage_engine_mguk_wear_percentage: str | int = 0
    damage_engine_tc_wear_percentage: str | int = 0
    damage_engine_blown: str | int = 0
    damage_engine_seized: str | int = 0
    history_number_of_laps_in_data: str | int = 0
    history_number_of_tyre_stints: str | int = 0
    history_best_lap_number: str | int = 0
    history_best_s1_lap_number: str | int = 0
    history_best_s2_lap_number: str | int = 0
    history_best_s3_lap_number: str | int = 0
    laphistory_last_lap_lap_time_ms: str | int = 0
    laphistory_last_lap_sector1_time_ms_component: str | int = 0
    laphistory_last_lap_sector1_time_minutes_component: str | int = 0
    laphistory_last_lap_sector2_time_ms_component: str | int = 0
    laphistory_last_lap_sector2_time_minutes_component: str | int = 0
    laphistory_last_lap_sector3_time_ms_component: str | int = 0
    laphistory_last_lap_sector3_time_minutes_component: str | int = 0
    laphistory_last_lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_s1lap_lap_time_ms: str | int = 0
    laphistory_fastest_s1lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_s1lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_s1lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_s1lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_s1lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_s1lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_s1lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_s2lap_lap_time_ms: str | int = 0
    laphistory_fastest_s2lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_s2lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_s2lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_s2lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_s2lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_s2lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_s2lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_s3lap_lap_time_ms: str | int = 0
    laphistory_fastest_s3lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_s3lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_s3lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_s3lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_s3lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_s3lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_s3lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_lap_time_ms: str | int = 0
    laphistory_fastest_lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_lap_lap_valid_bit_flags: str | int = 0
    tyresets_softs_number_of_new_available: str | int = 0
    tyresets_softs_number_of_used_available: str | int = 0
    tyresets_softs_best_actual_compound: str | int = 0
    tyresets_softs_best_wear: str | int = 0
    tyresets_softs_best_available: str | list = None
    tyresets_softs_best_recommended_session: str | int = 0
    tyresets_softs_best_life_span: str | int = 0
    tyresets_softs_best_usable_life: str | int = 0
    tyresets_softs_best_lap_delta_time: str | int = 0
    tyresets_mediums_number_of_new_available: str | int = 0
    tyresets_mediums_number_of_used_available: str | int = 0
    tyresets_mediums_best_actual_compound: str | int = 0
    tyresets_mediums_best_wear: str | int = 0
    tyresets_mediums_best_available: str | list = None
    tyresets_mediums_best_recommended_session: str | int = 0
    tyresets_mediums_best_life_span: str | int = 0
    tyresets_mediums_best_usable_life: str | int = 0
    tyresets_mediums_best_lap_delta_time: str | int = 0
    tyresets_hards_number_of_new_available: str | int = 0
    tyresets_hards_number_of_used_available: str | int = 0
    tyresets_hards_best_actual_compound: str | int = 0
    tyresets_hards_best_wear: str | int = 0
    tyresets_hards_best_available: str | list = None
    tyresets_hards_best_recommended_session: str | int = 0
    tyresets_hards_best_life_span: str | int = 0
    tyresets_hards_best_usable_life: str | int = 0
    tyresets_hards_best_lap_delta_time: str | int = 0
    tyresets_inters_number_of_new_available: str | int = 0
    tyresets_inters_number_of_used_available: str | int = 0
    tyresets_inters_best_actual_compound: str | int = 0
    tyresets_inters_best_wear: str | int = 0
    tyresets_inters_best_available: str | list = None
    tyresets_inters_best_recommended_session: str | int = 0
    tyresets_inters_best_life_span: str | int = 0
    tyresets_inters_best_usable_life: str | int = 0
    tyresets_inters_best_lap_delta_time: str | int = 0
    extmotion_suspension_rl_position: str | float = 0.0
    extmotion_suspension_rr_position: str | float = 0.0
    extmotion_suspension_fl_position: str | float = 0.0
    extmotion_suspension_fr_position: str | float = 0.0
    extmotion_suspension_rl_velocity: str | float = 0.0
    extmotion_suspension_rr_velocity: str | float = 0.0
    extmotion_suspension_fl_velocity: str | float = 0.0
    extmotion_suspension_fr_velocity: str | float = 0.0
    extmotion_suspension_rl_acceleration: str | float = 0.0
    extmotion_suspension_rr_acceleration: str | float = 0.0
    extmotion_suspension_fl_acceleration: str | float = 0.0
    extmotion_suspension_fr_acceleration: str | float = 0.0
    extmotion_wheel_rl_speed: str | float = 0.0
    extmotion_wheel_rr_speed: str | float = 0.0
    extmotion_wheel_fl_speed: str | float = 0.0
    extmotion_wheel_fr_speed: str | float = 0.0
    extmotion_wheel_rl_slip_ratio: str | float = 0.0
    extmotion_wheel_rr_slip_ratio: str | float = 0.0
    extmotion_wheel_fl_slip_ratio: str | float = 0.0
    extmotion_wheel_fr_slip_ratio: str | float = 0.0
    extmotion_wheel_rl_slip_angle: str | float = 0.0
    extmotion_wheel_rr_slip_angle: str | float = 0.0
    extmotion_wheel_fl_slip_angle: str | float = 0.0
    extmotion_wheel_fr_slip_angle: str | float = 0.0
    extmotion_wheel_rl_lat_force: str | float = 0.0
    extmotion_wheel_rr_lat_force: str | float = 0.0
    extmotion_wheel_fl_lat_force: str | float = 0.0
    extmotion_wheel_fr_lat_force: str | float = 0.0
    extmotion_wheel_rl_long_force: str | float = 0.0
    extmotion_wheel_rr_long_force: str | float = 0.0
    extmotion_wheel_fl_long_force: str | float = 0.0
    extmotion_wheel_fr_long_force: str | float = 0.0
    extmotion_height_of_cog_above_ground: str | float = 0.0
    extmotion_local_velocity_x: str | float = 0.0
    extmotion_local_velocity_y: str | float = 0.0
    extmotion_local_velocity_z: str | float = 0.0
    extmotion_angular_velocity_x: str | float = 0.0
    extmotion_angular_velocity_y: str | float = 0.0
    extmotion_angular_velocity_z: str | float = 0.0
    extmotion_angular_acceleration_x: str | float = 0.0
    extmotion_angular_acceleration_y: str | float = 0.0
    extmotion_angular_acceleration_z: str | float = 0.0
    extmotion_front_wheels_angle: str | float = 0.0
    extmotion_wheel_rl_vert_force: str | float = 0.0
    extmotion_wheel_rr_vert_force: str | float = 0.0
    extmotion_wheel_fl_vert_force: str | float = 0.0
    extmotion_wheel_fr_vert_force: str | float = 0.0
    extmotion_front_aero_height: str | float = 0.0
    extmotion_rear_aero_height: str | float = 0.0
    extmotion_front_roll_angle: str | float = 0.0
    extmotion_rear_roll_angle: str | float = 0.0
    extmotion_chassis_yaw: str | float = 0.0
    extmotion_chassis_pitch: str | float = 0.0
    extmotion_wheel_rl_camber: str | float = 0.0
    extmotion_wheel_rr_camber: str | float = 0.0
    extmotion_wheel_fl_camber: str | float = 0.0
    extmotion_wheel_fr_camber: str | float = 0.0
    extmotion_wheel_rl_camber_gain: str | float = 0.0
    extmotion_wheel_rr_camber_gain: str | float = 0.0
    extmotion_wheel_fl_camber_gain: str | float = 0.0
    extmotion_wheel_fr_camber_gain: str | float = 0.0
    positionhistory_position_history: str | int = 0


@dataclass
class AllCarsCollectedCar:
    aaa_car_idx: str | int = 0
    event_speedtrap_speed_kph: str | float = 0.0
    lapdata_last_lap_time_ms: str | int = 0
    lapdata_current_lap_time_ms: str | int = 0
    lapdata_sector1_time_ms_component: str | int = 0
    lapdata_sector1_time_minutes_component: str | int = 0
    lapdata_sector2_time_ms_component: str | int = 0
    lapdata_sector2_time_minutes_component: str | int = 0
    lapdata_delta_to_car_in_front_ms_component: str | int = 0
    lapdata_delta_to_car_in_front_minutes_component: str | int = 0
    lapdata_delta_to_leader_ms_component: str | int = 0
    lapdata_delta_to_leader_minutes_component: str | int = 0
    lapdata_lap_distance_travelled_m: str | float = 0.0
    lapdata_session_distance_travelled_m: str | float = 0.0
    lapdata_safety_car_delta: str | float = 0.0
    lapdata_car_position: str | int = 0
    lapdata_current_lap_number: str | int = 0
    lapdata_pit_status: str | int = 0
    lapdata_number_of_pit_stops: str | int = 0
    lapdata_sector: str | int = 0
    lapdata_current_lap_invalid: str | int = 0
    lapdata_penalties: str | int = 0
    lapdata_total_warnings: str | int = 0
    lapdata_corner_cutting_warnings: str | int = 0
    lapdata_number_unserved_drive_through_pens: str | int = 0
    lapdata_number_unserved_stop_go_pens: str | int = 0
    lapdata_grid_position: str | int = 0
    lapdata_driver_status: str | int = 0
    lapdata_result_status: str | int = 0
    lapdata_pit_lane_timer_active: str | int = 0
    lapdata_pit_lane_time_ms: str | int = 0
    lapdata_pit_lane_stop_time_ms: str | int = 0
    lapdata_pit_stop_must_serve_pen: str | int = 0
    lapdata_fastest_speed_trap_speed_kph: str | float = 0.0
    lapdata_fastest_speed_trap_lap: str | int = 0
    participants_is_ai_controlled_flag: str | int = 0
    participants_driver_id: str | int = 0
    participants_network_id: str | int = 0
    participants_team_id: str | int = 0
    participants_my_team_flag: str | int = 0
    participants_race_number: str | int = 0
    participants_nationality: str | int = 0
    participants_name: str = ""
    participants_network_telemetry_flag: str | int = 0
    participants_show_online_names: str | int = 0
    participants_f1_world_tech_level: str | int = 0
    participants_platform: str | int = 0
    participants_number_of_colours: str | int = 0
    participants_livery_red_1: str | int = 0
    participants_livery_green_1: str | int = 0
    participants_livery_blue_1: str | int = 0
    participants_livery_red_2: str | int = 0
    participants_livery_green_2: str | int = 0
    participants_livery_blue_2: str | int = 0
    participants_livery_red_3: str | int = 0
    participants_livery_green_3: str | int = 0
    participants_livery_blue_3: str | int = 0
    participants_livery_red_4: str | int = 0
    participants_livery_green_4: str | int = 0
    participants_livery_blue_4: str | int = 0
    telemetry_speed: str | int = 0
    telemetry_throttle: str | float = 0.0
    telemetry_steer: str | float = 0.0
    telemetry_brake: str | float = 0.0
    telemetry_clutch: str | int = 0
    telemetry_gear: str | int = 0
    telemetry_engine_rpm: str | int = 0
    telemetry_drs: str | int = 0
    status_actual_tyre_compound: str | int = 0
    status_visual_tyre_compound: str | int = 0
    status_tyre_age_laps: str | int = 0
    classification_position: str | int = 0
    classification_num_laps: str | int = 0
    classification_grid_position: str | int = 0
    classification_points: str | int = 0
    classification_num_pit_stops: str | int = 0
    classification_result_status: str | int = 0
    classification_result_reason: str | int = 0
    classification_best_lap_time_in_ms: str | int = 0
    classification_total_race_time: str | float = 0.0
    classification_penalties_time: str | int = 0
    classification_num_penalties: str | int = 0
    classification_num_tyre_stints: str | int = 0
    classification_tyre_stint_1_actual_tyre: str | int = 0
    classification_tyre_stint_1_visual_tyre: str | int = 0
    classification_tyre_stint_1_end_lap: str | int = 0
    classification_tyre_stint_2_actual_tyre: str | int = 0
    classification_tyre_stint_2_visual_tyre: str | int = 0
    classification_tyre_stint_2_end_lap: str | int = 0
    classification_tyre_stint_3_actual_tyre: str | int = 0
    classification_tyre_stint_3_visual_tyre: str | int = 0
    classification_tyre_stint_3_end_lap: str | int = 0
    classification_tyre_stint_4_actual_tyre: str | int = 0
    classification_tyre_stint_4_visual_tyre: str | int = 0
    classification_tyre_stint_4_end_lap: str | int = 0
    classification_tyre_stint_5_actual_tyre: str | int = 0
    classification_tyre_stint_5_visual_tyre: str | int = 0
    classification_tyre_stint_5_end_lap: str | int = 0
    classification_tyre_stint_6_actual_tyre: str | int = 0
    classification_tyre_stint_6_visual_tyre: str | int = 0
    classification_tyre_stint_6_end_lap: str | int = 0
    classification_tyre_stint_7_actual_tyre: str | int = 0
    classification_tyre_stint_7_visual_tyre: str | int = 0
    classification_tyre_stint_7_end_lap: str | int = 0
    classification_tyre_stint_8_actual_tyre: str | int = 0
    classification_tyre_stint_8_visual_tyre: str | int = 0
    classification_tyre_stint_8_end_lap: str | int = 0
    history_number_of_laps_in_data: str | int = 0
    history_number_of_tyre_stints: str | int = 0
    history_best_lap_number: str | int = 0
    history_best_s1_lap_number: str | int = 0
    history_best_s2_lap_number: str | int = 0
    history_best_s3_lap_number: str | int = 0
    laphistory_last_lap_lap_time_ms: str | int = 0
    laphistory_last_lap_sector1_time_ms_component: str | int = 0
    laphistory_last_lap_sector1_time_minutes_component: str | int = 0
    laphistory_last_lap_sector2_time_ms_component: str | int = 0
    laphistory_last_lap_sector2_time_minutes_component: str | int = 0
    laphistory_last_lap_sector3_time_ms_component: str | int = 0
    laphistory_last_lap_sector3_time_minutes_component: str | int = 0
    laphistory_last_lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_s1lap_lap_time_ms: str | int = 0
    laphistory_fastest_s1lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_s1lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_s1lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_s1lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_s1lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_s1lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_s1lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_s2lap_lap_time_ms: str | int = 0
    laphistory_fastest_s2lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_s2lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_s2lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_s2lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_s2lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_s2lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_s2lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_s3lap_lap_time_ms: str | int = 0
    laphistory_fastest_s3lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_s3lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_s3lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_s3lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_s3lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_s3lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_s3lap_lap_valid_bit_flags: str | int = 0
    laphistory_fastest_lap_time_ms: str | int = 0
    laphistory_fastest_lap_sector1_time_ms_component: str | int = 0
    laphistory_fastest_lap_sector1_time_minutes_component: str | int = 0
    laphistory_fastest_lap_sector2_time_ms_component: str | int = 0
    laphistory_fastest_lap_sector2_time_minutes_component: str | int = 0
    laphistory_fastest_lap_sector3_time_ms_component: str | int = 0
    laphistory_fastest_lap_sector3_time_minutes_component: str | int = 0
    laphistory_fastest_lap_lap_valid_bit_flags: str | int = 0
    positionhistory_position_history: str | int = 0
